"""Verify (and record the checksums of) the bespoke Stage-2a artifacts (V15c, ADR-0031, ADR-0024).

The bespoke engine loads three baked artifacts side by side — the two trained models and the matched
vocabulary manifest — from ``$SIBEI_BESPOKE_MODEL_DIR`` (dev) or the image's baked path
(``/opt/sibei/bespoke``). This is the ``fetch_weights.py`` pattern for that pair: neither artifact is
in version control (``out/`` is gitignored — the model comes off a GPU training run, the vocab is
regenerated by ``pnpm export:v15c-vocab``), so this script pins them by SHA-256 so a swapped or
mismatched artifact fails **here**, at build/verify time, rather than producing wrong coordinates
downstream (the same guarantee ADR-0023 asks of oemer's pinned weights).

Unlike oemer's checkpoints, these are not *downloaded*: the model is produced by training and the
vocab by the TypeScript exporter, so this script only **verifies** a directory it is pointed at. It is
run at image-build time after the artifacts are copied in (see the Dockerfile note), and can be run by
hand in dev to confirm a local ``out/v15b`` matches what was trained.

    python bespoke_weights.py --dir out/v15b
    python bespoke_weights.py                 # defaults to $SIBEI_BESPOKE_MODEL_DIR or /opt/sibei/bespoke

Updating the model is a deliberate act: retrain, drop the new ``model.onnx`` in, regenerate
``vocab.json``, then update ``ARTIFACTS`` below with the new size + digest in the same commit — so the
pin always describes the artifact the engine actually ships.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import sys

# filename -> (expected size in bytes, sha256). The vocab is deterministic (buildVocabulary, closed by
# construction); the models are the training artifacts — Stage 2a (out/v15b/model.onnx, ~7.4 MB
# CRNN+CTC, V15b) and Stage 1 (out/v16b/detect.onnx, ~1.8 MB centre-point detector, V16b). All three
# are baked side by side in the bespoke model dir.
ARTIFACTS = {
    "model.onnx": (7406608, "ca0174d6010e9d21d2bd595fccc31037093aab5e73f5fdb7284783a5411165c7"),
    "vocab.json": (9359, "bf02a789c2634c0b037a61962a8ddc5a9f4d30631b5dbd04ddaa044e8d945dc6"),
    "detect.onnx": (1771920, "03f1766886fe479c37927a22e00cce09973467da77b9cd51869a439b65080183"),
}


def sha256(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _default_dir() -> str:
    return os.environ.get("SIBEI_BESPOKE_MODEL_DIR") or "/opt/sibei/bespoke"


def verify(model_dir: str) -> int:
    ok = True
    for name, (size, digest) in ARTIFACTS.items():
        path = os.path.join(model_dir, name)
        if not os.path.isfile(path):
            print(f"MISSING: {path}", file=sys.stderr)
            ok = False
            continue
        got_size = os.path.getsize(path)
        got_digest = sha256(path)
        if got_size != size or got_digest != digest:
            print(
                f"CHECKSUM MISMATCH for {name}: expected {size} B {digest}, got {got_size} B {got_digest}",
                file=sys.stderr,
            )
            ok = False
        else:
            print(f"verified: {name} ({size} B)")
    return 0 if ok else 1


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="bespoke_weights", description=__doc__)
    parser.add_argument("--dir", default=_default_dir(), help="directory holding model.onnx + vocab.json")
    args = parser.parse_args(argv)
    return verify(args.dir)


if __name__ == "__main__":
    raise SystemExit(main())
