"""Fetch the bespoke model artifacts from their GitHub Release, verifying checksums (ADR-0033, ADR-0024).

The bespoke recogniser loads five baked artifacts side by side — the three trained ONNX models and
their two matched vocab manifests (see ``bespoke_weights.py``). None is in version control: ``out/`` is
gitignored, the models come off nondeterministic GPU training runs (a retrain is a *different* model, so
its bytes cannot be regenerated), and the vocabs are regenerated by the TypeScript exporters. That makes
a trained model an **irreplaceable artifact**, so the pinned set is published as immutable assets on a
GitHub Release and pulled here by checksum — exactly the ``fetch_weights.py`` pattern that fetches
oemer's weights, extended to our own models.

This runs at **build/dev time only** (e.g. the worker Dockerfile bakes the bespoke dir, ADR-0024); the
shipped worker loads the baked files and never calls the network at runtime (ADR-0001/0025). The repo is
public, so the download needs no auth (plain ``urllib``); ``GITHUB_TOKEN`` is used as a bearer only if
present, for rate-limit headroom.

    python fetch_bespoke.py                    # into $SIBEI_BESPOKE_MODEL_DIR or /opt/sibei/bespoke
    python fetch_bespoke.py --dir out/bespoke  # into an explicit dir
    python fetch_bespoke.py --dir out/bespoke --verify-only   # no download; just check what's there

The tag and the per-file (size, sha256) pins live in ``bespoke_weights.py`` and are bumped in one commit
when a model is retrained; this script is the matching *fetch* half of that *verify* half.
"""

from __future__ import annotations

import argparse
import os
import sys
import urllib.request

from bespoke_weights import ARTIFACTS, RELEASE_TAG, sha256, verify

REPO = os.environ.get("SIBEI_REPO", "leejianrong/sibei-score")


def _default_dir() -> str:
    return os.environ.get("SIBEI_BESPOKE_MODEL_DIR") or "/opt/sibei/bespoke"


def _asset_url(tag: str, name: str) -> str:
    return f"https://github.com/{REPO}/releases/download/{tag}/{name}"


def _download(url: str, dest: str) -> None:
    req = urllib.request.Request(url)
    # A token is optional (public repo). If present, it only buys rate-limit headroom; read by
    # reference from the environment and never logged.
    token = os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN")
    if token:
        req.add_header("Authorization", f"Bearer {token}")
    with urllib.request.urlopen(req) as resp, open(dest, "wb") as fh:  # noqa: S310 (fixed https host)
        while True:
            chunk = resp.read(1 << 20)
            if not chunk:
                break
            fh.write(chunk)


def fetch(model_dir: str, tag: str) -> int:
    os.makedirs(model_dir, exist_ok=True)
    for name, (size, digest) in ARTIFACTS.items():
        dest = os.path.join(model_dir, name)
        if os.path.isfile(dest) and os.path.getsize(dest) == size and sha256(dest) == digest:
            print(f"present: {name} ({size} B)")
            continue
        url = _asset_url(tag, name)
        print(f"downloading {name} <- {url}")
        _download(url, dest)
        got_size, got_digest = os.path.getsize(dest), sha256(dest)
        if got_size != size or got_digest != digest:
            print(
                f"CHECKSUM MISMATCH for {name}: expected {size} B {digest}, got {got_size} B {got_digest}",
                file=sys.stderr,
            )
            return 1
    # Belt-and-braces: re-verify the whole set the same way the build-time gate does.
    return verify(model_dir)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="fetch_bespoke", description=__doc__)
    parser.add_argument("--dir", default=_default_dir(), help="where to write the bespoke artifacts")
    parser.add_argument("--tag", default=RELEASE_TAG, help="the GitHub Release tag to pull (default: the pinned one)")
    parser.add_argument("--verify-only", action="store_true", help="do not download; just verify the target dir")
    args = parser.parse_args(argv)
    if args.verify_only:
        return verify(args.dir)
    return fetch(args.dir, args.tag)


if __name__ == "__main__":
    raise SystemExit(main())
